package Constant;

public class Constant {

    public int SEGMENT_SIZE = 4;
    public int AVP_CODE_SIZE =	4;
    public int AVP_FLAG_SIZE =	1;
    public int AVP_LENGTH_SIZE	= 3;
    public int AVP_FLAG_VENDOR_SPECIFIC = 0x80;
    public int AVP_FLAG_PROTECTED			=0x20;
    public int AVP_FLAG_MANDATORY =	0x40;

    public short IP_ADDRESS_FAMILY_IPV4 = 1;
    public short IP_ADDRESS_FAMILY_IPV6 = 2;



    public int DIAMETER_HEADER_VERSION_SIZE	=1;
    public int DIAMETER_HEADER_LENGTH_SIZE	=3;
    public int DIAMETER_HEADER_FLAG_SIZE	=1;
    public int DIAMETER_HEADER_COMMAND_CODE_SIZE = 3;
    public int DIAMETER_HEADER_APP_ID_SIZE = 4;
    public int DIAMETER_HEADER_HOP_BY_HOP_ID_SIZE = 4;
    public int DIAMETER_HEADER_END_TO_END_SIZE = 4;

    public int DIAMETER_HEADER_SIZE = DIAMETER_HEADER_VERSION_SIZE + DIAMETER_HEADER_LENGTH_SIZE + DIAMETER_HEADER_FLAG_SIZE + DIAMETER_HEADER_COMMAND_CODE_SIZE
            + DIAMETER_HEADER_APP_ID_SIZE + DIAMETER_HEADER_HOP_BY_HOP_ID_SIZE + DIAMETER_HEADER_END_TO_END_SIZE;


    public int AVP_CHILD_VENDOR_ID_SIZE	= 8;
    public int AVP_CHILD_CODE_SIZE			=4;
    public int AVP_CHILD_LENGTH_SIZE		=6;
    public int AVP_CHILD_FLAG_SIZE			=2;
    public int AVP_VENDOR_ID_SIZE	=4;
    public int AVP_CHILD_HEADER_SIZE	= (AVP_CHILD_CODE_SIZE + AVP_CHILD_FLAG_SIZE + AVP_CHILD_LENGTH_SIZE);
    public int AVP_HEADER_SIZE	= (AVP_CODE_SIZE + AVP_FLAG_SIZE + AVP_LENGTH_SIZE);

    public int DIAMETER_FLAG_REQUEST		=0x80;
    public int DIAMETER_FLAG_PROXYABLE		=0x40;
    public int DIAMETER_FLAG_ERROR			=0x20;
    public int DIAMETER_FLAG_TRANSMITTED 	=0x10;
    public char DIAMETER_CC_CAPABILITIES_EXCHANGE = 257;
    public int DIAMETER_AID_DIAMETER_COMMON_MESSAGE = 0;



}
